### ISSUE TITLE
 Unknown validator: 'DateValidator' (ArgumentError)

### ISSUE THREAD

**Issue by hopewise** [ka8725/redmine_s3#36]
Hello,

I have tried to install your pplugin, but then I have this error:

Any help is really applicated

```
 Unknown validator: 'DateValidator' (ArgumentError)
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activemodel-4.2.2/lib/active_model/validations/validates.rb:120:in `rescue in block in validates'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activemodel-4.2.2/lib/active_model/validations/validates.rb:117:in `block in validates'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activemodel-4.2.2/lib/active_model/validations/validates.rb:113:in `each'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activemodel-4.2.2/lib/active_model/validations/validates.rb:113:in `validates'
  /srv/redmine/app/models/version.rb:35:in `<class:Version>'
  /srv/redmine/app/models/version.rb:18:in `<top (required)>'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `require'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `block in require'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:240:in `load_dependency'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `require'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:360:in `require_or_load'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:494:in `load_missing_constant'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:184:in `const_missing'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:526:in `load_missing_constant'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:184:in `const_missing'
  /srv/redmine/app/models/attachment.rb:39:in `<class:Attachment>'
  /srv/redmine/app/models/attachment.rb:21:in `<top (required)>'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `require'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `block in require'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:240:in `load_dependency'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `require'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:360:in `require_or_load'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:494:in `load_missing_constant'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:184:in `const_missing'
  /srv/redmine/lib/plugins/redmine_s3/lib/redmine_s3.rb:8:in `<top (required)>'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `require'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `block in require'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:240:in `load_dependency'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `require'
  /srv/redmine/lib/plugins/redmine_s3/init.rb:1:in `block in <top (required)>'
```

**Comment by ka8725** [comment]
Try to run your redmine without the plugin. I think you will have the same issue.

**Comment by hopewise** [comment]
Redmine works fine, however we are downgrading to redmine version 2.6,
would redmine_s3 work fine with redmine 2.6? thanks

On Thu, Nov 26, 2015 at 5:30 AM, Andrey Koleshko <notifications@github.com>
wrote:

> Try to run your redmine without the plugin. I think you will have the same
> issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ka8725/redmine_s3/issues/36#issuecomment-159793598>.
>



-- 
--
Kind Regards,
---------------------------------------------
Samir Sabri
Software Architect& Developer
www.dcaclab.com
Jordan-Middle East

**Comment by ka8725** [comment]
The `DateValidator` exists in Redmine since [5 Jan 2013](https://github.com/redmine/redmine/commit/3e14c3017c037d93e562c3697cf50224dced7b50). And it exists in 2.6.0 version of redmine because it was release 1 year later: https://github.com/redmine/redmine/releases/tag/2.6.0

So the only reason of such issue is incorrect downgrade.

**Comment by UsmanMalik** [comment]
I am having the same issue with Rails application. 

```
usman@usman-Inspiron-3521:~/projects/Saloon$ ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
usman@usman-Inspiron-3521:~/projects/Saloon$ rails -v
Rails 4.2.5
usman@usman-Inspiron-3521:~/projects/Saloon$ 

```

Issue creating the object.

```

Loading development environment (Rails 4.2.5)
irb(main):001:0> c = Campaign.new
ArgumentError: Unknown validator: 'DateValidator'
    from /home/usman/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activemodel-4.2.5/lib/active_model/validations/validates.rb:120:in `rescue in block in validates'

```
